[package]
name = "rusty_classifiers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matfile = { version = "0.4.0", features = ["ndarray"] }
matfile-ndarray = "0.2.0"
ndarray = "0.15.6"
